# Day 12 Assignment: Hyperparameter Tuning for Time Series Forecasting

###Name: Divyashree R

This notebook performs hyperparameter tuning for stock price prediction.

The goal is to evaluate a few selected machine learning and deep learning models and identify the best performing configuration using evaluation metrics.

### Models Used
- K-Nearest Neighbors (KNN)
- Linear Regression
- LSTM (Deep Learning)

### Evaluation Metrics
- Mean Absolute Error (MAE)
- Root Mean Squared Error (RMSE)

The results of the experiments are saved into a CSV file and summarized for reporting.

Google Colab Link: https://colab.research.google.com/drive/1faHAD5VncbhN22ZW7jzu18pNR5vrMTZE?usp=sharing

In [ ]:
import numpy as np
import pandas as pd
from tqdm.auto import tqdm
from sklearn.model_selection import train_test_split
from copy import deepcopy

from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv('nifty50 25yrs.csv')
df.head()

         Date     Open     High      Low   Close
0  2000-01-03  1482.15  1592.90  1482.15  1592.2
1  2000-01-04  1594.40  1641.95  1594.40  1638.7
2  2000-01-05  1634.55  1635.50  1555.05  1595.8
3  2000-01-06  1595.80  1639.00  1595.80  1617.6
4  2000-01-07  1616.60  1628.25  1597.20  1613.3

In [2]:
def return_pairs(column, days):
    pricess = list(column)
    X = []
    y = []
    for i in range(len(pricess) - days):
        X.append(pricess[i:i+days])
        y.append(pricess[i+days])
    return np.array(X), np.array(y)

target_columns =  ['High']
day_chunks =  [30,60, 90]

chunked_data = {}

for col in target_columns:
    for days in day_chunks:
        key_X = f"X_{col}_{days}"
        key_y = f"y_{col}_{days}"
        X, y = return_pairs(df[col], days)
        chunked_data[key_X] = X
        chunked_data[key_y] = y


chunk_pairs = []

for key in chunked_data.keys():
    if key.startswith("X_"):
        y_key = key.replace("X_", "y_")
        if y_key in chunked_data:
            chunk_pairs.append([key, y_key])

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

def build_lstm(input_shape):
    model = Sequential([
        LSTM(50, activation='tanh', input_shape=input_shape),
        Dense(1)
    ])
    model.compile(optimizer='adam', loss='mse')
    return model

In [4]:
ml_models = [
    ("LinearRegression", LinearRegression()),
    ("KNN", KNeighborsRegressor())
]
dl_models = {
    "LSTM": build_lstm
}

In [7]:
trained_models = {}

for X, y in tqdm(chunk_pairs):
    X_data = chunked_data[X]
    y_data = chunked_data[y]

    X_train, X_test, y_train, y_test = train_test_split(
        X_data, y_data, test_size=0.1, random_state=42
    )

    # ML models
    for model_name, model in tqdm(ml_models):
        key = model_name + '_' + X[2:]
        model_copy = deepcopy(model)
        model_copy.fit(X_train, y_train)

        y_train_pred = model_copy.predict(X_train)
        y_test_pred = model_copy.predict(X_test)

        trained_models[key] = {
            'model': model_copy,
            'train_mae': mean_absolute_error(y_train, y_train_pred),
            'train_rmse': np.sqrt(mean_squared_error(y_train, y_train_pred)),
            'test_mae': mean_absolute_error(y_test, y_test_pred),
            'test_rmse': np.sqrt(mean_squared_error(y_test, y_test_pred))
        }

    # DL models
    from sklearn.preprocessing import MinMaxScaler
    scaler = MinMaxScaler()
    # scale input data
    X_train_scaled = scaler.fit_transform(X_train)
    X_test_scaled = scaler.transform(X_test)
    # reshape for LSTM
    X_train_rnn = np.expand_dims(X_train_scaled, -1)
    X_test_rnn = np.expand_dims(X_test_scaled, -1)

    for model_name, builder in tqdm(dl_models.items()):
        key = model_name + '_' + X[2:]
        model_dl = builder((X_train.shape[1], 1))

        model_dl.fit(X_train_rnn, y_train, epochs=50, batch_size=16, verbose=0)

        y_train_pred = model_dl.predict(X_train_rnn).flatten()
        y_test_pred = model_dl.predict(X_test_rnn).flatten()

        trained_models[key] = {
            'model': model_dl,
            'train_mae': mean_absolute_error(y_train, y_train_pred),
            'train_rmse': np.sqrt(mean_squared_error(y_train, y_train_pred)),
            'test_mae': mean_absolute_error(y_test, y_test_pred),
            'test_rmse': np.sqrt(mean_squared_error(y_test, y_test_pred))
        }

  0%|          | 0/3 [00:00<?, ?it/s]

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

177/177 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

  0%|          | 0/2 [00:00<?, ?it/s]

  0%|          | 0/1 [00:00<?, ?it/s]

176/176 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

In [8]:
results_df = pd.DataFrame([
    {"Model": name, **metrics}
    for name, metrics in trained_models.items()])

results_df.sort_values(by = 'test_mae', ascending = True).head(50)

,Model,model,train_mae,train_rmse,test_mae,test_rmse
0,LinearRegression_High_30,LinearRegression(),51.708919,84.334524,46.971744,81.336015
7,KNN_High_90,KNeighborsRegressor(),36.929140,58.769966,48.790144,74.204848
6,LinearRegression_High_90,LinearRegression(),51.720832,83.806338,49.204647,81.590714
3,LinearRegression_High_60,LinearRegression(),51.522225,84.223722,49.883383,80.417099
4,KNN_High_60,KNeighborsRegressor(),36.850899,58.333589,52.819089,82.674612
1,KNN_High_30,KNeighborsRegressor(),42.646429,68.669169,56.933037,89.679421
2,LSTM_High_30,"<Sequential name=sequential_3, built=True>",7049.559051,9436.732666,6530.364625,9019.327391
5,LSTM_High_60,"<Sequential name=sequential_4, built=True>",7103.051528,9488.383378,6621.541715,8979.809166
8,LSTM_High_90,"<Sequential name=sequential_5, built=True>",7115.020966,9489.357636,6814.539906,9197.865030

In [9]:
results_df.to_csv("models.csv", index=False)